//! Payload validation layer for outbound gRPC calls.
//!
//! Two severities are supported:
//!
//! * **Warnings** — always applied; logged via `tracing::warn!` and the call proceeds.
//!   Thresholds come from `ConnectionOptions::payload_warning_limits`.
//! * **Errors** — applied only when the [`ValidationContext`] carries `error_limits`,
//!   which the worker layer populates from the server's `DescribeNamespace` response.
//!   Errors short-circuit the call with `tonic::Status::invalid_argument`.
//!
//! The [`PayloadFieldValidator`] trait is *auto-generated from the proto descriptor set*
//! (see `crates/common/build.rs`). It has one required method per
//! `(message, direct-payload-field)` tuple discovered under `temporal.api.*`. The
//! hand-written [`DefaultPayloadFieldValidator`] supplies the actual logic for each
//! method — adding a new payload-bearing field to any `temporal.api.*` proto will
//! cause `impls.rs` to fail compilation until the new method is implemented.

mod impls;
mod limits;
mod outcome;

pub use impls::DefaultPayloadFieldValidator;
pub use limits::PayloadSizeLimits;
pub use outcome::{
    FieldValidationOutcome, Severity, ValidationContext, ValidationIssue, ValidationOutcome,
};

// Generated by crates/common/build.rs. Defines:
//   * `pub trait PayloadFieldValidator { ... }` — one required method per (message, field)
//   * `pub trait ValidateRequest { fn validate(&self, ...) -> ValidationOutcome; }`
//   * `impl ValidateRequest for <T>` for every gRPC request type and every payload-bearing
//     `temporal.api.*` message.
include!(concat!(env!("OUT_DIR"), "/payload_validation_impl.rs"));

#[cfg(test)]
mod tests {
    use super::*;
    use crate::protos::temporal::api::common::v1::{Payload, Payloads};
    use crate::protos::temporal::api::workflowservice::v1::StartWorkflowExecutionRequest;
    use std::collections::HashMap;

    /// Build a Payloads of a given encoded byte size (approximate — driven by data length).
    fn payloads_of(byte_count: usize) -> Payloads {
        Payloads {
            payloads: vec![Payload {
                metadata: HashMap::new(),
                data: vec![0u8; byte_count].into(),
                external_payloads: vec![],
            }],
        }
    }

    fn request_with_input(byte_count: usize) -> StartWorkflowExecutionRequest {
        let mut req = StartWorkflowExecutionRequest::default();
        req.input = Some(payloads_of(byte_count));
        req
    }

    #[test]
    fn payloads_under_warning_limit_produces_no_issues() {
        let warn = PayloadSizeLimits::new(1024, 1024);
        let ctx = ValidationContext::warnings_only(&warn);
        let req = request_with_input(64);
        let outcome = req.validate(&ctx, &DefaultPayloadFieldValidator);
        assert!(!outcome.has_warnings());
        assert!(!outcome.has_errors());
    }

    #[test]
    fn payloads_over_warning_limit_emits_warning_no_error() {
        let warn = PayloadSizeLimits::new(64, 1024);
        let ctx = ValidationContext::warnings_only(&warn);
        let req = request_with_input(512);
        let outcome = req.validate(&ctx, &DefaultPayloadFieldValidator);
        assert!(outcome.has_warnings(), "should emit a warning");
        assert!(!outcome.has_errors(), "client mode never blocks");
        assert!(outcome.to_status().is_none());
    }

    #[test]
    fn payloads_over_error_limit_blocks_in_worker_mode() {
        let warn = PayloadSizeLimits::new(64, 1024);
        let err = PayloadSizeLimits::new(256, 1024);
        let ctx = ValidationContext::with_error_limits(&warn, &err);
        let req = request_with_input(512);
        let outcome = req.validate(&ctx, &DefaultPayloadFieldValidator);
        assert!(outcome.has_warnings());
        assert!(outcome.has_errors(), "worker mode should block");
        let status = outcome.to_status().expect("blocking status");
        assert_eq!(status.code(), tonic::Code::InvalidArgument);
    }

    #[test]
    fn between_warning_and_error_warns_but_passes_in_worker_mode() {
        let warn = PayloadSizeLimits::new(64, 1024);
        let err = PayloadSizeLimits::new(2048, 1024);
        let ctx = ValidationContext::with_error_limits(&warn, &err);
        let req = request_with_input(512);
        let outcome = req.validate(&ctx, &DefaultPayloadFieldValidator);
        assert!(outcome.has_warnings());
        assert!(!outcome.has_errors());
        assert!(outcome.to_status().is_none());
    }

    #[test]
    fn zero_limit_disables_check() {
        let warn = PayloadSizeLimits::disabled();
        let ctx = ValidationContext::warnings_only(&warn);
        let req = request_with_input(10 * 1024 * 1024);
        let outcome = req.validate(&ctx, &DefaultPayloadFieldValidator);
        assert!(!outcome.has_warnings());
        assert!(!outcome.has_errors());
    }
}
